server:
  error:
    include-message: always
    include-binding-error: always

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login_registration_system
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    generate-ddl: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
